### PR TITLE
BOUNTY - Live faceswap opacity slider

### PR DESCRIPTION
**Pull request by KRSHH**
https://github.com/user-attachments/assets/8ca2c3cc-6e5a-4e9f-a18e-5bf0b5818174

## Summary by Sourcery

Add a live faceswap opacity slider to the webcam preview, enabling users to control the opacity of the swapped face. Refactor the UI to accommodate the new slider, enhancing the overall user interface structure.

New Features:
- Introduce a live faceswap opacity slider in the webcam preview interface, allowing users to adjust the opacity of the swapped face in real-time.

Enhancements:
- Refactor the webcam preview setup to include a main frame that organizes the preview label and the new opacity slider for better UI structure.

### CODE REVIEW

**Comment by hacksider** [comment]
Looks really good but I suggest putting the opacity on the Menu as it will be problematic once you try to capture the window. :)

**Comment by KRSHH** [comment]
Users crop the window from OBS to remove the preview title from the live window anyways... so they can probably crop that too

**Comment by hacksider** [comment]
One of the reason we also dont want to put any controls on the preview is to ensure you dont have to switch to any windows when doing any stuffs. The goal is to make everything controllable in a single panel (and sometimes you have to hover the mouse so it will capture the details in there as well, it will be a very bad user experience)

**Comment by KRSHH** [comment]
Check now

**Comment by KRSHH** [comment]
https://github.com/user-attachments/assets/181089ea-df37-4155-b8b9-6952c02ea684

**Comment by hacksider** [comment]
Awesome! I sent you a dm!

**Pull request merged**
