### PR TITLE
Added support for multiple faces

### PR DESCRIPTION
**Pull request by pereiraroland26**
*Added ability to map unique source face to each unique target faces.
*Functionality works for image, video and webcam targets.
*Functionality can be enabled by toggling 'Map faces' on the ui.

## Summary by Sourcery

Add functionality to map unique source faces to unique target faces for images, videos, and webcam inputs. This feature can be toggled via the UI and involves new UI components and clustering logic to handle face mapping efficiently.

New Features:
- Introduce support for mapping unique source faces to unique target faces across images, videos, and webcam inputs, with a toggle option in the UI to enable this feature.

Enhancements:
- Add new UI elements to support face mapping, including pop-up windows for selecting source and target images.
- Implement clustering and centroid analysis to identify and map unique faces in video frames.

Documentation:
- Update README to include the new '--map-faces' command-line option for mapping source and target faces.

### CODE REVIEW

**Comment by hacksider** [comment]
This is one of the best commits I've seen so far! Thanks bro!

**Comment by hacksider** [comment]
@pereiraroland26 Hi there bro, do you have a paypal account? can you drop your paypal account here? Thanks!

**Comment by pereiraroland26** [comment]
> @pereiraroland26 Hi there bro, do you have a paypal account? can you drop your paypal account here? Thanks!

Sorry, I don't use paypal. Maybe you can send me an amazon gift card?

**Comment by hacksider** [comment]
Will try to send you one this week once I get back from the vacation ☺️

Thanks for the contribution ☺️

**Comment by hacksider** [comment]
Can you send me an email? My address is on my profile.

**Pull request merged**
