### PR TITLE
BOUNTY - Mouth Masking

### PR DESCRIPTION
**Pull request by GhoulBoii**
~~The menu is a bit messed up at the moment. I will try fixing it in the morning.~~ UI has been made uniform with the switches being added with the others. I did limited testing on my workstation and it worked. However, the live preview was coming frame-by-frame so couldn't test in a real world environment.

## Summary by Sourcery

Implement mouth masking feature to enhance face swapping by preserving the original mouth area. Update the UI to include controls for toggling mouth mask options.

New Features:
- Introduce mouth masking functionality to preserve the original mouth area during face swapping.

Enhancements:
- Add UI elements to toggle and display mouth mask options, including switches in the main and preview windows.

### CODE REVIEW

**Comment by GhoulBoii** [comment]
@sourcery-ai review

**Comment by GhoulBoii** [comment]
@sourcery-ai review

**Comment by hacksider** [comment]
Hello @GhoulBoii , will review this tomorrow as theres a typhoon in our area. 🥲 Thanks for this push! Will send the bounty as soon as I have checked this.

**Comment by GhoulBoii** [comment]
> Hello @GhoulBoii , will review this tomorrow as theres a typhoon in our area. 🥲 Thanks for this push! Will send the bounty as soon as I have checked this.

No problem! Stay safe and thanks for the bounty.

**Comment by hacksider** [comment]
Hi there @GhoulBoii , as per testing mouth mask is not working properly.
image 😢

**Comment by hacksider** [comment]
Will be closing this until a new working pull request is submitted.

**Pull request closed without merging**
