### PR TITLE
UI, D&D, Opacity, Hotswap

### PR DESCRIPTION
**Pull request by KRSHH**
## Summary by Sourcery

Enhance the UI with a new dropdown menu and reorganize layout for better usability. Add features for saving and loading switch states, and implement face opacity and mouth mask in face swapping. Update documentation with new media paths and additional guidance.

New Features:
- Introduce a new ModernOptionMenu class for improved UI dropdown functionality.
- Add functionality to save and load switch states to a JSON file for persistent settings.
- Implement face opacity and mouth mask features in the face swapping process.

Enhancements:
- Refactor UI layout to separate options into left and right columns for better organization.
- Improve error handling in the preview initialization process.
- Enhance the face swapping process with additional features like opacity and mouth mask.

Documentation:
- Update README with new media paths and additional usage tips.
- Add new sections in the README for better user guidance and feature explanation.

### CODE REVIEW

**Comment by hacksider** [comment]
Awesome work @KRSHH but there's still frame dips on the new theme. 

https://github.com/user-attachments/assets/23495085-1d90-4497-8d92-c6b7416174cc


https://github.com/user-attachments/assets/9b127668-97fe-4028-bf12-8ce4e4b62eb5

See comparison video on the push

**Comment by Cesarsilva000** [comment]
what is mask size and mask feather pls

**Comment by KRSHH** [comment]
> what is mask size and mask feather pls

This PR is still not there. use main

**Comment by Cesarsilva000** [comment]
i don't get what you mean by main but bro i used yours/pulled yours into my project and its working very well, in terms of performance with my GPU i was having performance issues with the main one and also some issues with the slider but this one is working perfectly, but i don't know what mask size and mask feather is so i wanted to know if its something that will help me, the "show fps" button really helped me out honestly thansk

**Comment by KRSHH** [comment]
> i don't get what you mean by main but bro i used yours/pulled yours into my project and its working very well, in terms of performance with my GPU i was having performance issues with the main one and also some issues with the slider but this one is working perfectly, but i don't know what mask size and mask feather is so i wanted to know if its something that will help me, the "show fps" button really helped me out honestly thansk

Mask size is the size of the cropping of mouth region from faceswap and feather is the smoothening of it.

How much FPS are you getting on main compared to this?

**Comment by Cesarsilva000** [comment]
thanks, I'm getting at least 4 times more fps when I use this one with CUDA or tensorrt when i was using main I was getting max 0.8 fps with my NVIDIA RTX 6GB graphics card(on main CUDA isnt working so i could only use CPU), when i used this I'm getting from 2.9 to 6fps on CUDA and tensorrt, using CPU gives me like 1.8, now the difference between 0.8 and 2.9 fps is very big and its more than enough for me 
i just need to find a good webcam because some webcams slow it down so thanks a lot

**Comment by hexxt-git** [comment]
it seems like the repo maintainers actively try to keep its quality down, the install complicated and push for a paid compiled version but i could be misunderstanding things. thankfully there better forks

**Comment by hacksider** [comment]
You can actually use this if you want but I won't be pushing anything that will make everything slower @hexxt-git ☺️

**Pull request closed without merging**
