### PR TITLE
add onnxslim support

### PR DESCRIPTION
**Pull request by inisis**
## Summary by Sourcery

Update README.md to provide additional instructions for optimizing the inswapper_128_fp16.onnx model using onnxslim.

Documentation:
- Updated README.md to include instructions for optimizing the inswapper_128_fp16.onnx model using onnxslim.

### CODE REVIEW

**Comment by hacksider** [comment]
As per checking, it just doesn't work based on the description

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\My Pc\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "E:\Deep-Live-Cam\Deep-Live-Cam\modules\ui.py", line 172, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview(camera_variable.get(), virtual_cam_out_value.get()))
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\modules\ui.py", line 442, in webcam_preview
    preview_running = webcam_preview_loop(camera, source_image, frame_processors)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\modules\ui.py", line 365, in webcam_preview_loop
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 58, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 47, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
           ^^^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 43, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=modules.globals.execution_providers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\venv\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "E:\Deep-Live-Cam\Deep-Live-Cam\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "E:\Deep-Live-Cam\Deep-Live-Cam\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from E:\Deep-Live-Cam\Deep-Live-Cam\modules\..\models\inswapper_128.onnx failed:D:\a\_work\1\s\onnxruntime\core\graph\model.cc:150 onnxruntime::Model::Model Unsupported model IR version: 10, max supported IR version: 9

**Comment by inisis** [comment]
and if you want to use the slimmed model, it's preferred to slim under the same environment.

**Comment by inisis** [comment]
@hacksider is there any updates, I have tested and it really works.

**Comment by inisis** [comment]
@hacksider Hi, is there any updates?

**Pull request closed without merging**
