### PR TITLE
UI Change

### PR DESCRIPTION
**Pull request by KRSHH**
UI Change

## Summary by Sourcery

Update the README.md file to correct the description of a contributor's work on the project.

Documentation:
- Update README.md to correct the description of GosuDRM's contribution from 'uncensoring roop' to 'open version of roop'.

### CODE REVIEW

**Comment by hacksider** [comment]
Yup, I just confirmed the second commit have issues with the map faces. the current working one is this :)
image

**Comment by KRSHH** [comment]
What issue are you facing?? any error messages?

**Comment by KRSHH** [comment]
Still working flawlessly on my end - 
https://streamable.com/nealzh

**Comment by KRSHH** [comment]
Try it Now, check if its working now

**Pull request merged**
