### PR TITLE
Better UI

### PR DESCRIPTION
**Pull request by KRSHH**
This PR introduces a significant overhaul of the user interface, focusing on a more modern aesthetic and a more intuitive layout. 

**Key Changes:**

- **Modern Design Language:** Implemented a modern design language using CustomTkinter's capabilities, featuring a dark theme, updated color palettes, and rounded corners for buttons and frames.
- **Improved Layout:**  Reorganized the main window using a grid layout for better organization and responsiveness. Source and target sections are now clearly separated, with options and buttons neatly arranged below.
- **Enhanced Drag-and-Drop:** Drag-and-drop functionality is now more visually consistent with the new design.
- **Responsive Preview:** The preview window is now more responsive, resizing dynamically with the window size.
- **Clearer Mapping Interface:** The face mapping popup has been redesigned with a cleaner table-like structure, making it easier to understand and interact with.
- **Increased Resolution:** Default preview resolution is increased to 1280x720 for better visual clarity.
- **Minor Bug Fixes:**  Fixed minor bugs related to image updates and UI element placements.

qetgwsrg

### CODE REVIEW

**Comment by hacksider** [comment]
@KRSHH Looks really good but can you align the switches. We don't want too many movements when choosing between the tabs. For user experience, it will be better to just either move horizontal or vertical, not diagonal. Thanks in advance dude! Really makes the UI looks fresh :)

**Comment by KRSHH** [comment]
> @KRSHH Looks really good but can you align the switches. We don't want too many movements when choosing between the tabs. For user experience, it will be better to just either move horizontal or vertical, not diagonal. Thanks in advance dude! Really makes the UI looks fresh :)

I just made them all vertical.
+Make me a collaborator

**Comment by KRSHH** [comment]
@hacksider

**Comment by nothiin** [comment]
What happened?

**Comment by KRSHH** [comment]
What happened?

**Comment by hacksider** [comment]
I have to undo the commit as per testing the "face mapping" stopped working. Will have to do a thorough test on it on a fork of mine, this is what happens when I got too excited on new features 🤣

**Comment by KRSHH** [comment]
Its working fine on my end tho...

**Comment by KRSHH** [comment]
All the features are working fine, even the face mapper (In my testing)

**Pull request merged**
