### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KRSHH**
Fix formatting, structure etc.

## Summary by Sourcery

Update the README.md file to enhance readability and clarity by restructuring sections, refining language, and providing more concise installation and usage instructions.

Documentation:
- Revise README.md to improve formatting and structure, including clearer section headings and streamlined instructions for installation and usage.

### CODE REVIEW

**Comment by hacksider** [comment]
Dude you're on fire today 😆

**Comment by KRSHH** [comment]
haha, doing this shit instead of prepping for exams

**Comment by KRSHH** [comment]
Yup gonna go offline for few weeks now... and on a side note add in that avgpcdemo GIF  in the readme

**Comment by hacksider** [comment]
Will do, also, Goodluck on your exams!

**Comment by KRSHH** [comment]
Thanks!

**Pull request merged**
