### PR TITLE
Two face feature and multi target face placement control

### PR DESCRIPTION
**Pull request by iVideoGameBoss**
### Two Face Feature and Face Controls
Added a new feature that can work with two faces in source image and replace two target faces on webcam, video or image. You can select a source image that has one or two faces. Left face in source image will replace left target face and right face in source image will replace right target face. You can also control how one face is replaced if two target faces are on webcam, video or image from left or right. 

### Two faces replaced on webcam

DemoTwoFace

### Works with Video and Images 

DemoTwoFace

### Face placement controls

FaceControls

**Show both faces** - When you select a source image with two faces you will need to enable this option to replace both target faces on webcam, video or image. By default left face is always used. If your video has one target face or two target faces and one target face goes out of frame than left face is always used on target face.

**Flip left/right faces** - Turning on this option will flip source faces on target faces to right->left. You can flip both source faces in your webcam, video or image when two target faces are present. By default left face will replace left target face and right face will replace right target face.

**Detect face from right** - Turning on this option will replace target face detected from right of frame when two target faces are present. By default the target face/s is detected from left of webcam, video or image.

## Summary by Sourcery

Add a new feature to support replacing two target faces using a source image with one or two faces. Implement face placement controls to customize face replacement behavior. Update documentation to reflect these changes and guide contributors.

New Features:
- Introduce a two-face feature that allows replacing two target faces on a webcam, video, or image using a source image with one or two faces.
- Add face placement controls to manage how faces are replaced, including options to show both faces, flip left/right faces, and detect faces from the right.

Enhancements:
- Improve face detection by adding functions to get the leftmost and rightmost faces from a source image.
- Refactor the process_frame function to handle multiple faces and apply face swapping based on new controls.

Documentation:
- Update README.md to include instructions and examples for the new two-face feature and face placement controls.
- Add a CONTRIBUTING.md file to guide contributors on the workflow for pushing changes.

### CODE REVIEW

**Comment by vic4key** [comment]
@iVideoGameBoss Thank you for the pull request. Before I do a merging into the branch, could you please update the codes to support multiple faces? This will ensure the feature is more versatile and can handle various scenarios. Thanks!

**Comment by iVideoGameBoss** [comment]
> @iVideoGameBoss Thank you for the pull request. Before I do a merging into the branch, could you please update the codes to support multiple faces? This will ensure the feature is more versatile and can handle various scenarios. Thanks!

The code can already handle multi faces. The many face feature still works like before. The source face is loaded as two rather than one. So it does not matter if you have one source face or two source faces. The program detects first source from from left and second source face from right. So even when you have one source face it still loads up one source face as two. 

In my code when you use two source faces and have two faces on target frame, it will replace first found face from left of frame and second found face from right of frame. If for any reason the second face goes out of frame it will then use left source face as default.  You can flip which source face to use with the 'flip left/right faces' even when one source face is present in target.

Because you can use one source face or two source faces, the program works just like before. You can use the many face option like before and all faces will be replaced with left source face. So if you have two source faces, the left source faces is used by default. But you can flip which source face to use with the 'flip left/right faces'. So when you have two source faces and flip them , the second face will be used by many face option.

It does not matter how many faces are shown on target frame. When you have two source faces or even one and the 'show both face' option on, The first detected face from left of frame is used to replace with left source face. Then first detected face from right of frame is replaced with right source face. So if your target frame has three or more people. The most left face will be replaced and the most right face will be replaced on target frame. So in this scenario if use the many face feature the left source face is used by default, As mention before if you have two sources faces you can flip and have many face feature use right source face.

So the program is working just like before , the only change really here is when you load up source face it is always loaded as two faces no mater if two faces are present.

**Comment by iVideoGameBoss** [comment]
> @iVideoGameBoss Thank you for the pull request. Before I do a merging into the branch, could you please update the codes to support multiple faces? This will ensure the feature is more versatile and can handle various scenarios. Thanks!

I added two face flip support to many face option. So when you have two faces in source image and one, two or more faces in target. You can flip between the two faces on many face option. As mentioned above, when you have one source face it will also be loaded as second face. So when you flip a face it still remains same face and will work with many face option.

**Comment by vic4key** [comment]
@iVideoGameBoss Sorry for the late reply. This function takes time to review when I'm busy, so I cannot reply quickly.

Your PR seem only support two faces, it seems does not cover to support multiple faces. The design should:
1. List all person faces in the image/video/frame.
2. Add a UI to pick the replacement face for each one to create a list of face mappings.
3. Then, based on this mapping, swap faces during Start/Live.

This will ensure the feature is more versatile and can handle various scenarios, and better for maintaining the codes later.

I appreciate your contribution, but If you do not have time to update your codes. Please wait for support of the multiple faces in the later version. Thanks.

**Comment by hacksider** [comment]
@iVideoGameBoss just want to ask if you want to be a collaborator of this repo :) I saw you're doing a lot of stuffs and I want the community to see your visions as well.

**Comment by iVideoGameBoss** [comment]
> @iVideoGameBoss just want to ask if you want to be a collaborator of this repo :) I saw you're doing a lot of stuffs and I want the community to see your visions as well.

sure. that would be really cool

**Pull request closed without merging**
