### PR TITLE
Fixed the Face mapper issue in Live Cam - New UI PR

### PR DESCRIPTION
**Pull request by KRSHH**
I thought there was an issue in video face swap mapper, not the Live Cam. Now its definitely fixed.

*Adding image for first time after bootup on live mapper, takes 3 extra seconds. and adding images AFTER the first one WON'T take any extra time.

fixed (2) (2)

## Summary by Sourcery

Fix the face mapper issue in the Live Cam by addressing pop-up handling and invalid file selection. Enhance the UI with specific button classes and image labels for better user interaction, and refactor image label updates for efficiency.

Bug Fixes:
- Fix the issue with the face mapper in the Live Cam by ensuring proper handling of pop-up windows and invalid target files.

Enhancements:
- Improve the UI by using specific button classes like SourceMapperButton and DragDropButton for better functionality.
- Add labels for source and target images in the UI to enhance user experience.
- Refactor the code to handle image label updates more efficiently by directly accessing the row frame's children.

### CODE REVIEW

**Comment by hacksider** [comment]
Awesome! Will test it now :)

**Comment by hacksider** [comment]
Awesome! Thanks Man!

**Comment by hacksider** [comment]
image
Just added you to the main credits 😄

**Comment by KRSHH** [comment]
Thanks,  can you add this GIF for the UI change and avg PC performance show, the first one is a little misleading -
demo-gif

**Pull request merged**
