### PR TITLE
BOUNTY - Webcam Merged (tested)

### PR DESCRIPTION
**Pull request by GhoulBoii**
## Summary by Sourcery

Add camera selection and face opacity adjustment features to the UI, enhancing the webcam preview functionality. Update the README to reflect completed tasks and introduce a bug report template for better issue tracking.

New Features:
- Introduce a camera selection feature in the UI, allowing users to choose from available cameras for webcam preview.
- Add a face opacity slider to the UI, enabling users to adjust the transparency of the face overlay in real-time.

Enhancements:
- Improve the webcam preview functionality by allowing dynamic camera index selection and handling camera opening errors.
- Enhance the UI/UX for the desktop application as noted in the README updates.

Documentation:
- Update the README to reflect the completion of multiple faces support and UI/UX enhancements for the desktop app.

Chores:
- Add a bug report issue template to the GitHub repository to standardize bug reporting.

### CODE REVIEW

**Comment by hacksider** [comment]
Hi there, as per testing it's throwing errors.

`TypeError: webcam_preview() missing 1 required positional argument: 'camera_index'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\My Pc\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "E:\Deep-Live-Cam\Deep-Live-Cam\modules\ui.py", line 410, in <lambda>
    command=lambda: webcam_preview(root),
                    ^^^^^^^^^^^^^^^^^^^^
TypeError: webcam_preview() missing 1 required positional argument: 'camera_index'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\My Pc\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "E:\Deep-Live-Cam\Deep-Live-Cam\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "E:\Deep-Live-Cam\Deep-Live-Cam\modules\ui.py", line 410, in <lambda>
    command=lambda: webcam_preview(root),
                    ^^^^^^^^^^^^^^^^^^^^
TypeError: webcam_preview() missing 1 required positional argument: 'camera_index'`

**Comment by GhoulBoii** [comment]
@sourcery-ai review

**Comment by hacksider** [comment]
Still same error after testing :)
image

**Comment by GhoulBoii** [comment]
> Still same error after testing :) image

Could you try git pulling the repo once? I can see that I am calling the function with the correct arguements on my side.

**Comment by hacksider** [comment]
Awesome! Works really well! Can you put your paypal link here?

**Comment by GhoulBoii** [comment]
> Awesome! Works really well! Can you put your paypal link here?

Hi, I sent you an email because I wasn't comfortable sending my paypal email. Could you check to see if you received it?

**Pull request merged**
